CourseProjects/CourseProjects/VisualStudioProjects/ASP/AspMvcExamplesAndExercises/CourseBookingStandaloneCS/Controllers/CourseCatalogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CourseBookingStandaloneCS.Models;
using CourseBookingStandaloneCS.DataAccess;

namespace CourseBookingStandaloneCS.Controllers {
    public class CourseCatalogController : Controller {
        public CourseCatalogController(ITrainingCourseDAO dao) {
            this.dao = dao;
        }

        public ActionResult Index() {
            ViewData.Model = dao.GetAllCourses();
            return View();
        }

        public ActionResult ByNumber(string number) {
            TrainingCourse course = dao.GetCourseByNumber(number);
            if (course != null) {
                ViewData.Model = course;
                return View();
            } else {
                string errorMsg = String.Format("No Course With the Number '{0}'", number);
                ViewData.Model = errorMsg;
                return View("NoResults");
            }
        }

        public ActionResult ByKeyword(string keyword) {
            IQueryable<TrainingCourse> courses = dao.GetCoursesContainingText(keyword);
            if (courses.ToList().Count != 0) {
                ViewData["keyword"] = keyword;
                ViewData.Model = courses;
                return View();
            } else {
                string errorMsg = String.Format("No Courses Contain the Keyword '{0}'", keyword);
                ViewData.Model = errorMsg;
                return View("NoResults");
            }
        }

        [AcceptVerbs(HttpVerbs.Get)]
        public ActionResult NewCourse() {
            return View("NewCourse");
        }

        [AcceptVerbs(HttpVerbs.Post)]
        public ActionResult NewCourse(string number, string title, string type) {
            dao.AddCourse(new TrainingCourse() {Number = number, Title = title, Type = type});
            ViewData["message"] = "Course Created Sccessfully!";
            ViewData.Model = dao.GetCourseByNumber(number);
            return View("NewCourseCreated");
        }

        private readonly ITrainingCourseDAO dao;
    }
}

CourseProjects/CourseProjects/VisualStudioProjects/ASP/AspMvcExamplesAndExercises/CourseBookingStandaloneCS/Views/CourseCatalog/ByKeyword.cshtml
@model IQueryable<CourseBookingStandaloneCS.Models.TrainingCourse>

@{
    ViewBag.Title = "Resuts of 'Search By Keyword'";
}

<h1>Courses Containing the Keyword <em>@ViewData["keyword"]</em></h1>
<table>
    <thead>
        <tr><th>Number</th><th>Title</th><th>Type</th></tr>
    </thead>
    <tbody>
        @foreach (var course in ViewData.Model) {
            <tr>
                <td>
                    @Html.ActionLink(Html.Encode(course.Number), "ByNumber", "CourseCatalog", new { Number = course.Number }, new { })
                </td>
                <td>@Html.Encode(course.Title)</td>
                <td>@Html.Encode(course.Type)</td>
            </tr>
        }
    </tbody>
</table>

CourseProjects/CourseProjects/VisualStudioProjects/ASP/AspMvcExamplesAndExercises/CourseBookingStandaloneCS/Views/CourseCatalog/ByNumber.cshtml
@model CourseBookingStandaloneCS.Models.TrainingCourse

@{
    ViewBag.Title = "The Course You Selected";
    var course = ViewData.Model;
}
<h1>Details of the Course You Selected </h1>
<table>
    <tbody>
        <tr>
            <th>Number</th>
            <td>@course.Number</td>
        </tr>
        <tr>
            <th>Title</th>
            <td>@course.Title</td>
        </tr>
        <tr>
            <th>Type</th>
            <td>@course.Type</td>
        </tr>
    </tbody>
</table>

CourseProjects/CourseProjects/VisualStudioProjects/ASP/AspMvcExamplesAndExercises/CourseBookingStandaloneCS/Views/CourseCatalog/Index.cshtml
@model IQueryable<CourseBookingStandaloneCS.Models.TrainingCourse>

@{
    ViewBag.Title = "Our Course Catalog";
}

<h1>The Complete Course Catalog</h1>
<table>
    <thead>
        <tr><th>Number</th><th>Title</th><th>Type</th></tr>
    </thead>
    <tbody>    
    @foreach(var course in ViewData.Model) {
            <tr>
                <td>
                    @Html.ActionLink(Html.Encode(course.Number), "ByNumber", "CourseCatalog", new { Number = course.Number }, new { })
                </td>
                <td>@Html.Encode(course.Title)</td>
                <td>@Html.Encode(course.Type)</td>
            </tr>
     }
    </tbody>
</table>

CourseProjects/CourseProjects/VisualStudioProjects/ASP/AspMvcExamplesAndExercises/CourseBookingStandaloneCS/Views/CourseCatalog/NewCourse.cshtml
@{
    ViewBag.Title = "NewCourse";
}

<h1>Enter the Details of the New Course Below</h1>
@using(Html.BeginForm()) {
    <table>
        <tr>
            <th>Number</th>
            <td>@Html.TextBox("Number")</td>
            <td>@Html.ValidationMessage("Number")</td>
        </tr>
        <tr>
            <th>Title</th>
            <td>@Html.TextBox("Title")</td>
            <td>@Html.ValidationMessage("Title")</td>
        </tr>
        <tr>
            <th>Type</th>
            <td>@Html.TextBox("Type")</td>
            <td>@Html.ValidationMessage("Type")</td>
        </tr>
        <tr>
            <td colspan="3">
                <input type="submit" value="Add Course"/>
            </td>
        </tr>
    </table>
}

CourseProjects/CourseProjects/VisualStudioProjects/ASP/AspMvcExamplesAndExercises/CourseBookingStandaloneCS/Views/CourseCatalog/NewCourseCreated.cshtml
@model CourseBookingStandaloneCS.Models.TrainingCourse

@{
    ViewBag.Title = "The Course You Created";
    var course = ViewData.Model;
}
<h1>Details of the Course You Have Created</h1>
<table>
    <tbody>
        <tr>
            <th>Number</th>
            <td>@course.Number</td>
        </tr>
        <tr>
            <th>Title</th>
            <td>@course.Title</td>
        </tr>
        <tr>
            <th>Type</th>
            <td>@course.Type</td>
        </tr>
    </tbody>
</table>